# config/onboarding_workflow.yaml
workflow_type: "CustomerOnboarding"
workflow_version: "1.0"
initial_state_model: "state_models.OnboardingState"

steps:
  - name: "Create_User_Profile"
    type: "STANDARD"
    function: "workflow_utils.create_user_profile"
    input_model: "state_models.CreateUserProfileInput" # <-- NEW
    dependencies: []
    automate_next: true
    dynamic_injection:
      rules:
        - condition_key: "email_domain" 
          value_is_not: ["gmail.com", "yahoo.com", "outlook.com"]
          action: "INSERT_AFTER_CURRENT"
          steps_to_insert:
            - name: "Verify_Email"
              type: "ASYNC"
              function: "workflow_utils.verify_email_address"
              automate_next: true
            - name: "Update Database"
              type: "ASYNC"
              function: "workflow_utils.set_compliance_alert_db"
              automate_next: true
              
  - name: "Send_Welcome_Email"
    type: "ASYNC"
    function: "workflow_utils.send_welcome_email"
    dependencies: ["Create_User_Profile"]
    automate_next: true
