"""RAFT Trainer — creates a fine-tuned Ollama model from RAFT training data.

Wraps `ollama create ruvon-expert` using the Ollama REST API.
The trained model name includes a version hash derived from the training dataset,
enabling staleness detection when docs are updated.

Model naming: ruvon-expert-{dataset_hash[:8]}
  The RAFTRouter checks this hash against the current index manifest hash.
  If they differ, it downgrades to RAG and warns the operator to retrain.
"""

from __future__ import annotations

import hashlib
import logging
import subprocess
import tempfile
from pathlib import Path
from typing import Optional

logger = logging.getLogger(__name__)

_MODELFILE_TEMPLATE = """\
FROM {base_model}
SYSTEM You are an expert Ruvon SDK workflow architect.
You have deep knowledge of Ruvon step types, governance rules, YAML workflow
definitions, saga patterns, edge device constraints, and fintech compliance.
Always cite documentation when answering with ##begin_quote## markers.
If the provided context does not contain the answer, say "I don't know."
Think step-by-step before giving a final answer.
"""


class RAFTTrainer:
    """Creates a fine-tuned Ollama model from an Alpaca JSONL dataset."""

    def __init__(self, ollama_base_url: str = "http://localhost:11434"):
        self.ollama_base_url = ollama_base_url

    def dataset_version_hash(self, dataset_path: Path) -> str:
        """Return an 8-char hash of the dataset file contents for model versioning."""
        return hashlib.sha256(dataset_path.read_bytes()).hexdigest()[:8]

    def versioned_model_name(self, dataset_path: Path, base: str = "ruvon-expert") -> str:
        """Return a versioned model name: ruvon-expert-{hash}."""
        return f"{base}-{self.dataset_version_hash(dataset_path)}"

    def create_model(
        self,
        dataset_path: Path,
        base_model: str = "llama3",
        output_model: Optional[str] = None,
        ollama_base_url: Optional[str] = None,
    ) -> str:
        """Create a fine-tuned Ollama model from a RAFT JSONL dataset.

        Args:
            dataset_path: Path to Alpaca JSONL file generated by RAFTDatasetGenerator.
            base_model:   Ollama base model to fine-tune from.
            output_model: Output model name (defaults to versioned name).
            ollama_base_url: Override Ollama URL.

        Returns:
            The name of the created model.

        Raises:
            RuntimeError: If Ollama is not running or model creation fails.
        """
        if not dataset_path.exists():
            raise FileNotFoundError(f"Dataset not found: {dataset_path}")

        base_url = ollama_base_url or self.ollama_base_url
        model_name = output_model or self.versioned_model_name(dataset_path)

        # Build Modelfile content
        modelfile = _MODELFILE_TEMPLATE.format(base_model=base_model)

        # Append training data as TRAIN blocks
        dataset_text = dataset_path.read_text(encoding="utf-8")
        train_blocks = self._dataset_to_train_blocks(dataset_text)
        modelfile += train_blocks

        # Write Modelfile to a temp file and call ollama create
        with tempfile.NamedTemporaryFile(
            mode="w", suffix=".Modelfile", delete=False, encoding="utf-8"
        ) as f:
            f.write(modelfile)
            modelfile_path = f.name

        logger.info("[RAFTTrainer] Creating model '%s' from '%s'", model_name, base_model)
        logger.info("[RAFTTrainer] Dataset: %s (%d bytes)", dataset_path, dataset_path.stat().st_size)

        try:
            result = subprocess.run(
                ["ollama", "create", model_name, "-f", modelfile_path],
                capture_output=True,
                text=True,
                timeout=600,  # 10 minutes max
            )
            if result.returncode != 0:
                raise RuntimeError(
                    f"ollama create failed (exit {result.returncode}):\n"
                    f"stdout: {result.stdout}\n"
                    f"stderr: {result.stderr}"
                )
            logger.info("[RAFTTrainer] Model '%s' created successfully", model_name)
        finally:
            Path(modelfile_path).unlink(missing_ok=True)

        return model_name

    def list_ruvon_models(self) -> list[str]:
        """Return all ruvon-expert model versions available in Ollama."""
        try:
            import httpx
            resp = httpx.get(f"{self.ollama_base_url}/api/tags", timeout=5.0)
            resp.raise_for_status()
            return [
                m["name"]
                for m in resp.json().get("models", [])
                if "ruvon-expert" in m["name"]
            ]
        except Exception as e:
            logger.warning("[RAFTTrainer] Could not list Ollama models: %s", e)
            return []

    def is_stale(self, dataset_path: Path, base: str = "ruvon-expert") -> bool:
        """Return True if no Ollama model matches the current dataset hash."""
        expected = self.versioned_model_name(dataset_path, base)
        return expected not in self.list_ruvon_models()

    @staticmethod
    def _dataset_to_train_blocks(dataset_jsonl: str) -> str:
        """Convert Alpaca JSONL to Ollama Modelfile TRAIN MESSAGE blocks."""
        import json
        blocks: list[str] = []
        for line in dataset_jsonl.strip().splitlines():
            line = line.strip()
            if not line:
                continue
            try:
                sample = json.loads(line)
                instruction = sample.get("instruction", "")
                context = sample.get("input", "")
                answer = sample.get("output", "")
                if instruction and answer:
                    user_msg = f"{instruction}\n\n{context}".strip() if context else instruction
                    blocks.append(
                        f'\nMESSAGE user {user_msg}\n'
                        f'MESSAGE assistant {answer}'
                    )
            except json.JSONDecodeError:
                continue
        return "\n".join(blocks) + "\n"
