[pytest]
norecursedirs = original_implementation_files confucius examples
addopts = --import-mode=importlib
asyncio_mode = auto
markers =
    integration: marks tests as integration tests (deselect with '-m "not integration"')