# config/image_compliance_workflow.yaml

#workflow_type: "ImageComplianceWorkflow"
#workflow_version: "1.0"
#initial_state_model: "state_models.ImageComplianceState"
#
#steps:
#  - name: "Collect_Compliance_Assets"
#    type: "STANDARD"
#    function: "workflow_utils.collect_compliance_assets"
#    required_input: ["image_url", "compliance_text"]
#    dependencies: []
#
#  - name: "Run_Image_Compliance_Agent"
#    type: "ASYNC"
#    function: "workflow_utils.run_image_compliance_agent"
#    dependencies: ["Collect_Compliance_Assets"]
#    dynamic_injection:
#      rules:
#        - condition_key: "analysis_result"
#          value_match: "NON_COMPLIANT"
#          action: "INSERT_AFTER_CURRENT"
#          steps_to_insert:
#            - name: "Send_Compliance_Alert_Email"
#              type: "ASYNC"
#              function: "workflow_utils.send_compliance_alert"
#            - name: "Set_Compliance_Status_Database"
#              type: "ASYNC"
#              function: "workflow_utils.set_compliance_alert_db"
#              dependencies: ["Send_Compliance_Alert_Email"]
#  - name: "Generate_Final_Decision"
#    type: "STANDARD"
#    function: "workflow_utils.noop"
#    dependencies: [ "Run_Image_Compliance_Agent" ]
#
#
#







workflow_type: "ImageComplianceWorkflow"
workflow_version: "1.0"
initial_state_model: "state_models.ImageComplianceState"

steps:
  - name: "Collect_Compliance_Assets"
    type: "STANDARD"
    function: "workflow_utils.collect_compliance_assets"
    input_model: "state_models.ImageComplianceCollectComplianceAssetsInput"
    dependencies: []

  - name: "Run_Image_Compliance_Agent"
    type: "ASYNC"
    function: "workflow_utils.run_image_compliance_agent"
    dependencies: ["Collect_Compliance_Assets"]
    dynamic_injection:
      rules:
        - condition_key: "analysis_result"
          value_match: "NON_COMPLIANT"
          action: "INSERT_AFTER_CURRENT"
          steps_to_insert:
            - name: "Run_Concurrent_Alerts"
              type: "PARALLEL"
              tasks:
                - name: "Send_Compliance_Alert_Email"
                  function: "workflow_utils.send_compliance_alert"
                - name: "Set_Compliance_Status_Database"
                  function: "workflow_utils.set_compliance_alert_db"

  - name: "Generate_Final_Decision"
    type: "STANDARD"
    function: "workflow_utils.noop"
    dependencies: [ "Run_Image_Compliance_Agent" ]