#!/usr/bin/env python3
"""
Worker Registration Script

Registers a Celery worker as an edge device with the Rufus control plane.

Usage:
    python register_worker.py --device-id worker-01 --gpu

Environment Variables:
    RUFUS_CONTROL_PLANE_URL - Control plane API URL (default: http://localhost:8000)
"""

import argparse
import os
import sys
import json
import httpx
from typing import Optional


def register_worker(
    device_id: str,
    control_plane_url: str,
    device_name: Optional[str] = None,
    gpu: bool = False,
    memory_gb: int = 8,
    cpu_cores: Optional[int] = None,
    region: str = "us-east-1",
    zone: str = "us-east-1a",
    worker_pool: str = "default",
) -> dict:
    """
    Register a Celery worker as an edge device.

    Args:
        device_id: Unique worker identifier
        control_plane_url: Control plane API URL
        device_name: Human-readable worker name
        gpu: Whether worker has GPU capability
        memory_gb: Worker memory in GB
        cpu_cores: Number of CPU cores
        region: AWS region or data center
        zone: Availability zone
        worker_pool: Celery worker pool name

    Returns:
        dict: Registration response with api_key

    Raises:
        httpx.HTTPError: If registration fails
    """
    if device_name is None:
        device_name = f"Celery Worker {device_id}"

    if cpu_cores is None:
        import multiprocessing
        cpu_cores = multiprocessing.cpu_count()

    # Build capabilities
    capabilities = {
        "gpu": gpu,
        "memory_gb": memory_gb,
        "cpu_cores": cpu_cores,
        "region": region,
        "zone": zone,
        "worker_pool": worker_pool,
    }

    if gpu:
        # Add GPU-specific capabilities
        capabilities.update({
            "gpu_model": os.getenv("GPU_MODEL", "unknown"),
            "cuda_version": os.getenv("CUDA_VERSION", "unknown"),
        })

    # Registration payload
    payload = {
        "device_id": device_id,
        "device_type": "celery_worker",
        "device_name": device_name,
        "merchant_id": "internal",
        "firmware_version": "1.0.0",
        "sdk_version": "1.0.0",
        "location": zone,
        "capabilities": capabilities,
    }

    # Send registration request
    url = f"{control_plane_url}/api/v1/workers/register"

    with httpx.Client() as client:
        response = client.post(url, json=payload, timeout=10.0)
        response.raise_for_status()

    return response.json()


def save_worker_config(device_id: str, registration_data: dict, output_file: Optional[str] = None):
    """
    Save worker configuration to file.

    Args:
        device_id: Worker identifier
        registration_data: Registration response data
        output_file: Output file path (default: .env.{device_id})
    """
    if output_file is None:
        output_file = f".env.{device_id}"

    api_key = registration_data.get("api_key")
    config_url = registration_data.get("config_url")
    sync_url = registration_data.get("sync_url")

    env_content = f"""# Worker Configuration for {device_id}
# Generated by register_worker.py

# Rufus Control Plane
RUFUS_CONTROL_PLANE_URL={registration_data.get('control_plane_url', 'http://localhost:8000')}
RUFUS_API_KEY={api_key}
RUFUS_ENCRYPTION_KEY=changeme  # CHANGE THIS IN PRODUCTION

# Worker Settings
WORKER_DB_PATH=/var/lib/rufus/worker_{device_id}.db
CONFIG_POLL_INTERVAL=60
SYNC_INTERVAL=30
HEARTBEAT_INTERVAL=60

# Celery Settings
CELERY_BROKER_URL=redis://localhost:6379/0
CELERY_RESULT_BACKEND=redis://localhost:6379/0

# Worker Identity
WORKER_ID={device_id}
WORKER_REGION={registration_data.get('region', 'us-east-1')}
WORKER_ZONE={registration_data.get('zone', 'us-east-1a')}

# API Endpoints
CONFIG_URL={config_url}
SYNC_URL={sync_url}
"""

    with open(output_file, 'w') as f:
        f.write(env_content)

    print(f"\n✅ Configuration saved to: {output_file}")
    print(f"\nTo start worker:")
    print(f"  export $(cat {output_file} | xargs)")
    print(f"  celery -A examples.celery_edge_worker.rufus_worker_edge worker --loglevel=info")


def main():
    parser = argparse.ArgumentParser(
        description="Register Celery worker as edge device",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  # Register standard worker
  python register_worker.py --device-id worker-01

  # Register GPU worker
  python register_worker.py --device-id worker-gpu-01 --gpu --memory-gb 64

  # Register worker in EU region
  python register_worker.py --device-id worker-eu-01 --region eu-central-1 --zone eu-central-1a

Environment Variables:
  RUFUS_CONTROL_PLANE_URL  Control plane API URL (default: http://localhost:8000)
        """
    )

    parser.add_argument(
        "--device-id",
        required=True,
        help="Unique worker identifier (e.g., worker-01)"
    )

    parser.add_argument(
        "--device-name",
        help="Human-readable worker name"
    )

    parser.add_argument(
        "--control-plane-url",
        default=os.getenv("RUFUS_CONTROL_PLANE_URL", "http://localhost:8000"),
        help="Control plane API URL (default: http://localhost:8000)"
    )

    parser.add_argument(
        "--gpu",
        action="store_true",
        help="Worker has GPU capability"
    )

    parser.add_argument(
        "--memory-gb",
        type=int,
        default=8,
        help="Worker memory in GB (default: 8)"
    )

    parser.add_argument(
        "--cpu-cores",
        type=int,
        help="Number of CPU cores (default: auto-detect)"
    )

    parser.add_argument(
        "--region",
        default="us-east-1",
        help="AWS region or data center (default: us-east-1)"
    )

    parser.add_argument(
        "--zone",
        default="us-east-1a",
        help="Availability zone (default: us-east-1a)"
    )

    parser.add_argument(
        "--worker-pool",
        default="default",
        help="Celery worker pool name (default: default)"
    )

    parser.add_argument(
        "--output",
        help="Output file for worker config (default: .env.{device_id})"
    )

    parser.add_argument(
        "--json",
        action="store_true",
        help="Output JSON instead of saving to file"
    )

    args = parser.parse_args()

    try:
        print(f"📡 Registering worker: {args.device_id}")
        print(f"   Control Plane: {args.control_plane_url}")
        print(f"   GPU: {args.gpu}")
        print(f"   Memory: {args.memory_gb} GB")
        print(f"   Region: {args.region} / {args.zone}")
        print()

        registration_data = register_worker(
            device_id=args.device_id,
            control_plane_url=args.control_plane_url,
            device_name=args.device_name,
            gpu=args.gpu,
            memory_gb=args.memory_gb,
            cpu_cores=args.cpu_cores,
            region=args.region,
            zone=args.zone,
            worker_pool=args.worker_pool,
        )

        if args.json:
            # Output JSON
            print(json.dumps(registration_data, indent=2))
        else:
            # Save to file
            print("✅ Worker registered successfully!")
            print(f"\n📋 Registration Details:")
            print(f"   Device ID: {registration_data['device_id']}")
            print(f"   API Key: {registration_data['api_key'][:20]}... (secret)")
            print(f"   Config URL: {registration_data['config_url']}")
            print(f"   Sync URL: {registration_data['sync_url']}")

            save_worker_config(args.device_id, registration_data, args.output)

            print("\n⚠️  IMPORTANT: Save the API key securely!")
            print("   The API key is shown only once and cannot be retrieved later.")

    except httpx.HTTPError as e:
        print(f"\n❌ Registration failed: {e}", file=sys.stderr)
        if hasattr(e, 'response') and e.response:
            print(f"\nResponse: {e.response.text}", file=sys.stderr)
        sys.exit(1)

    except Exception as e:
        print(f"\n❌ Error: {e}", file=sys.stderr)
        sys.exit(1)


if __name__ == "__main__":
    main()
