"""Stage 7 — Output Renderer: converts the validated workflow dict to a YAML string."""

from __future__ import annotations

import logging
from datetime import datetime, timezone
from typing import TYPE_CHECKING, Any, Dict, Optional

from rufus.builder_ai.models import LintReport

if TYPE_CHECKING:
    from rufus.builder_ai.knowledge.raft_router import RetrievalDecision

logger = logging.getLogger(__name__)


class OutputRenderer:
    """Stage 7: Render a workflow dict to a YAML string with provenance header."""

    def render(
        self,
        workflow: Dict[str, Any],
        original_prompt: str,
        lint_report: Optional[LintReport],
        pipeline_version: str = "0.1.0",
        decision: "Optional[RetrievalDecision]" = None,
        privacy_level: str = "balanced",
        pii_redactions: int = 0,
    ) -> str:
        import yaml

        # Inject workflow_builder_meta step
        meta_step = {
            "name": "_builder_meta",
            "type": "WORKFLOW_BUILDER_META",
            "automate_next": True,
            "meta_config": {
                "generated_by": "rufus-workflow-builder/0.1",
                "original_prompt": original_prompt,
                "pipeline_version": pipeline_version,
                "model_versions": {},
                "lint_results": _lint_summary(lint_report),
                "human_reviewed": False,
            },
        }
        steps = workflow.get("steps", [])
        # Prepend meta step
        workflow_with_meta = {**workflow, "steps": [meta_step] + steps}

        # Build header comment
        now = datetime.now(timezone.utc).strftime("%Y-%m-%d")
        if lint_report:
            lint_line = f"Lint: PASS ({lint_report.passed}/{len(lint_report.results)} rules)"
            if lint_report.warned:
                lint_line += f" | {lint_report.warned} warning(s)"
            if lint_report.has_errors:
                lint_line += f" | {lint_report.failed} ERROR(s)"
        else:
            lint_line = "Lint: skipped"

        # RAG/privacy provenance line
        if decision is not None:
            rag_line = (
                f"# retrieval_strategy: {decision.strategy.value}"
                f"  |  confidence: {decision.confidence:.2f}"
                f"  |  privacy_level: {privacy_level}"
                f"  |  chunks_sent_to_cloud: {str(decision.chunks_sent_to_cloud).lower()}"
                f"  |  pii_redactions: {pii_redactions}\n"
            )
        else:
            rag_line = f"# retrieval_strategy: none  |  privacy_level: {privacy_level}\n"

        header = (
            f"# Generated by rufus-workflow-builder/0.1\n"
            f"# Original prompt: {original_prompt!r}\n"
            f"# {lint_line}  |  Generated: {now}\n"
            f"{rag_line}\n"
        )

        yaml_body = yaml.dump(workflow_with_meta, default_flow_style=False, sort_keys=False, allow_unicode=True)
        return header + yaml_body


def _lint_summary(lint_report: Optional[LintReport]) -> Dict[str, Any]:
    if lint_report is None:
        return {"skipped": True}
    return {
        "passed": lint_report.passed,
        "warned": lint_report.warned,
        "failed": lint_report.failed,
    }
