"""Add workflow_execution_logs table

Revision ID: 441ed90ac861
Revises: d08b401e4c86
Create Date: 2026-02-16 16:49:32.310754

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '441ed90ac861'
down_revision: Union[str, None] = 'd08b401e4c86'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('edge_devices',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('device_id', sa.String(length=100), nullable=False),
    sa.Column('device_type', sa.String(length=50), nullable=False),
    sa.Column('device_name', sa.String(length=200), nullable=True),
    sa.Column('merchant_id', sa.String(length=100), nullable=True),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('api_key_hash', sa.String(length=64), nullable=False),
    sa.Column('public_key', sa.Text(), nullable=True),
    sa.Column('firmware_version', sa.String(length=50), nullable=True),
    sa.Column('sdk_version', sa.String(length=50), nullable=True),
    sa.Column('capabilities', sa.Text(), server_default='[]', nullable=True),
    sa.Column('status', sa.String(length=50), server_default='online', nullable=True),
    sa.Column('metadata', sa.Text(), server_default='{}', nullable=True),
    sa.Column('last_heartbeat_at', sa.DateTime(), nullable=True),
    sa.Column('last_sync_at', sa.DateTime(), nullable=True),
    sa.Column('registered_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_edge_devices'))
    )
    with op.batch_alter_table('edge_devices', schema=None) as batch_op:
        batch_op.create_index('ix_device_heartbeat', ['last_heartbeat_at'], unique=False)
        batch_op.create_index('ix_device_merchant', ['merchant_id'], unique=False)
        batch_op.create_index('ix_device_status', ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_edge_devices_device_id'), ['device_id'], unique=True)

    op.create_table('workflow_execution_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('workflow_id', sa.String(length=36), nullable=False),
    sa.Column('execution_id', sa.String(length=36), nullable=True),
    sa.Column('step_name', sa.String(length=200), nullable=True),
    sa.Column('log_level', sa.String(length=20), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('metadata', sa.Text(), nullable=True),
    sa.Column('logged_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workflow_execution_logs'))
    )
    with op.batch_alter_table('workflow_execution_logs', schema=None) as batch_op:
        batch_op.create_index('ix_execution_logs_level', ['log_level'], unique=False)
        batch_op.create_index('ix_execution_logs_time', ['logged_at'], unique=False)
        batch_op.create_index('ix_execution_logs_workflow', ['workflow_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_workflow_execution_logs_workflow_id'), ['workflow_id'], unique=False)

    op.create_table('device_commands',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('device_id', sa.String(length=100), nullable=False),
    sa.Column('command_type', sa.String(length=100), nullable=False),
    sa.Column('command_data', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=50), server_default='pending', nullable=True),
    sa.Column('priority', sa.Integer(), server_default='5', nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('delivered_at', sa.DateTime(), nullable=True),
    sa.Column('executed_at', sa.DateTime(), nullable=True),
    sa.Column('result', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['edge_devices.device_id'], name=op.f('fk_device_commands_device_id_edge_devices'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_device_commands'))
    )
    with op.batch_alter_table('device_commands', schema=None) as batch_op:
        batch_op.create_index('ix_command_created', ['created_at'], unique=False)
        batch_op.create_index('ix_command_device_status', ['device_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_device_commands_device_id'), ['device_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('device_commands', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_device_commands_device_id'))
        batch_op.drop_index('ix_command_device_status')
        batch_op.drop_index('ix_command_created')

    op.drop_table('device_commands')
    with op.batch_alter_table('workflow_execution_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workflow_execution_logs_workflow_id'))
        batch_op.drop_index('ix_execution_logs_workflow')
        batch_op.drop_index('ix_execution_logs_time')
        batch_op.drop_index('ix_execution_logs_level')

    op.drop_table('workflow_execution_logs')
    with op.batch_alter_table('edge_devices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_edge_devices_device_id'))
        batch_op.drop_index('ix_device_status')
        batch_op.drop_index('ix_device_merchant')
        batch_op.drop_index('ix_device_heartbeat')

    op.drop_table('edge_devices')
    # ### end Alembic commands ###
